Model

In [ ]:
from keras.models import Sequential
from keras.layers import Dense,Flatten,Conv2D,MaxPool2D,BatchNormalization,Dropout,Input,GlobalMaxPool2D
from keras import regularizers
from keras import optimizers

In [ ]:
model=Sequential()
model.add(Input(shape=(164,164,3)))
model.add(Conv2D(32,(3,3),activation='relu',padding='same'))
model.add(Conv2D(32,(3,3),activation='relu',padding='same'))
model.add(BatchNormalization())
model.add(MaxPool2D(2))
model.add(Conv2D(64,(3,3),activation='relu'))
model.add(Dropout(0.2))
model.add(Conv2D(128,(3,3),activation='relu'))
model.add(BatchNormalization())
model.add(MaxPool2D(2))
#model.add(Conv2D(256,(3,3),activation='relu'))
model.add(Conv2D(256,(3,3),activation='relu'))
model.add(BatchNormalization())
model.add(MaxPool2D(2))
model.add(Dropout(0.3))
model.add(GlobalMaxPool2D())
model.add(Dense(128,activation='relu'))
model.add(Dropout(0.3))
model.add(Dense(44,activation='softmax'))

In [ ]:
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_5 (Conv2D)            (None, 164, 164, 32)      896       
_________________________________________________________________
conv2d_6 (Conv2D)            (None, 164, 164, 32)      9248      
_________________________________________________________________
batch_normalization_3 (Batch (None, 164, 164, 32)      128       
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 82, 82, 32)        0         
_________________________________________________________________
conv2d_7 (Conv2D)            (None, 80, 80, 64)        18496     
_________________________________________________________________
dropout_3 (Dropout)          (None, 80, 80, 64)        0         
_________________________________________________________________
conv2d_8 (Conv2D)            (None, 78, 78, 128)      

In [ ]:
model.compile(optimizer=optimizers.Adam(),loss='categorical_crossentropy',metrics=['accuracy'])

In [ ]:
from keras.models import load_model
model=load_model('/content/drive/MyDrive/All fruits/temp2/FruitsNewLatestBestModel5.h5')
model.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
conv2d_5 (Conv2D)            (None, 164, 164, 32)      896       
_________________________________________________________________
conv2d_6 (Conv2D)            (None, 164, 164, 32)      9248      
_________________________________________________________________
batch_normalization_3 (Batch (None, 164, 164, 32)      128       
_________________________________________________________________
max_pooling2d_3 (MaxPooling2 (None, 82, 82, 32)        0         
_________________________________________________________________
conv2d_7 (Conv2D)            (None, 80, 80, 64)        18496     
_________________________________________________________________
dropout_3 (Dropout)          (None, 80, 80, 64)        0         
_________________________________________________________________
conv2d_8 (Conv2D)            (None, 78, 78, 128)      

In [ ]:
from keras.callbacks import ModelCheckpoint,EarlyStopping
early_stopper = EarlyStopping(monitor='val_accuracy', min_delta=0, patience=10, verbose=1)
checkpoint = ModelCheckpoint('/content/drive/MyDrive/All fruits/temp2/FruitsNewLatestBestModel6.h5', monitor='val_accuracy', verbose=1, save_best_only=True,
                                 mode='auto')

In [ ]:
history=model.fit(X_train,y_train,epochs=40,validation_data=(X_test,y_test),callbacks=[checkpoint,early_stopper])

Epoch 1/40
991/991 [==============================] - 238s 192ms/step - loss: 0.9403 - accuracy: 0.7087 - val_loss: 1.0057 - val_accuracy: 0.7181

Epoch 00001: val_accuracy improved from -inf to 0.71807, saving model to /content/drive/MyDrive/All fruits/temp2/FruitsNewLatestBestModel5.h5
Epoch 2/40
991/991 [==============================] - 184s 186ms/step - loss: 0.9117 - accuracy: 0.7188 - val_loss: 1.0233 - val_accuracy: 0.7157

Epoch 00002: val_accuracy did not improve from 0.71807
Epoch 3/40
991/991 [==============================] - 184s 186ms/step - loss: 0.8916 - accuracy: 0.7267 - val_loss: 1.0251 - val_accuracy: 0.7162

Epoch 00003: val_accuracy did not improve from 0.71807
Epoch 4/40
991/991 [==============================] - 185s 187ms/step - loss: 0.8821 - accuracy: 0.7281 - val_loss: 1.0112 - val_accuracy: 0.7222

Epoch 00004: val_accuracy improved from 0.71807 to 0.72223, saving model to /content/drive/MyDrive/All fruits/temp2/FruitsNewLatestBestModel5.h5
Epoch 5/40
991/

In [ ]:
history=model.fit(X_train,y_train,epochs=20,validation_data=(X_test,y_test),callbacks=[checkpoint,early_stopper])

Epoch 1/20
991/991 [==============================] - 187s 189ms/step - loss: 0.5898 - accuracy: 0.8126 - val_loss: 0.9194 - val_accuracy: 0.7586

Epoch 00001: val_accuracy did not improve from 0.75960
Epoch 2/20
991/991 [==============================] - 185s 187ms/step - loss: 0.5732 - accuracy: 0.8161 - val_loss: 0.9408 - val_accuracy: 0.7588

Epoch 00002: val_accuracy did not improve from 0.75960
Epoch 3/20
991/991 [==============================] - 184s 186ms/step - loss: 0.5734 - accuracy: 0.8143 - val_loss: 0.9314 - val_accuracy: 0.7546

Epoch 00003: val_accuracy did not improve from 0.75960
Epoch 4/20
991/991 [==============================] - 185s 187ms/step - loss: 0.5640 - accuracy: 0.8208 - val_loss: 0.9325 - val_accuracy: 0.7523

Epoch 00004: val_accuracy did not improve from 0.75960
Epoch 5/20
991/991 [==============================] - 184s 186ms/step - loss: 0.5719 - accuracy: 0.8175 - val_loss: 0.9333 - val_accuracy: 0.7585

Epoch 00005: val_accuracy did not improve fro

In [ ]:
model.evaluate(X_test,y_test)

331/331 [==============================] - 9s 27ms/step - loss: 0.9715 - accuracy: 0.7826


[0.9715221524238586, 0.782592236995697]

Model Evaluation

In [ ]:
label_fruit_map={0: 'acerola',
 1: 'apple',
 2: 'apricot',
 3: 'banana',
 4: 'black_berry',
 5: 'blueberry',
 6: 'carambola',
 7: 'coconut',
 8: 'custard_apple',
 9: 'date',
 10: 'dragon',
 11: 'fig',
 12: 'gooseberry',
 13: 'grape',
 14: 'guava',
 15: 'jackfruit',
 16: 'jambul',
 17: 'jujube',
 18: 'kiwi',
 19: 'kumquat',
 20: 'lime',
 21: 'loquat',
 22: 'lychee',
 23: 'mamey_apple',
 24: 'mango',
 25: 'muskmelon',
 26: 'olive',
 27: 'orange',
 28: 'papaya',
 29: 'pear',
 30: 'pineapple',
 31: 'plumcot',
 32: 'pomegranate',
 33: 'quince',
 34: 'rambutan',
 35: 'sapodilla',
 36: 'strawberry',
 37: 'ugli',
 38: 'watermelon',
 39: 'white_mulberry',
 40: 'nance',
 41: 'zucchini',
 42: 'manila tamarind',
 43: 'lillipilli',
 44: 'monstera deliciosa',
 45: 'rimu',
 46: 'ita palm',
 47: 'malay apple',
 48: 'cardon',
 49: 'pulasan'}

In [ ]:
import numpy as np
X_train=np.load(open('/content/drive/MyDrive/All fruits/temp2/final_new_latest_X_train1.npy','rb'))
X_test=np.load(open('/content/drive/MyDrive/All fruits/temp2/final_new_latest_X_test1.npy','rb'))
y_train=np.load(open('/content/drive/MyDrive/All fruits/temp2/final_new_latest_y_train1.npy','rb'))
y_test=np.load(open('/content/drive/MyDrive/All fruits/temp2/final_new_latest_y_test1.npy','rb'))

In [ ]:
X_train.shape,X_test.shape,y_train.shape,y_test.shape

((31710, 164, 164, 3), (10570, 164, 164, 3), (31710, 44), (10570, 44))

In [ ]:
import keras
model=keras.models.load_model('/content/drive/MyDrive/All fruits/temp2/FruitsNewLatestBestModel5.h5')

In [ ]:
y_train_pred=model.predict(X_train)
y_test_pred=model.predict(X_test)

In [ ]:
y_train_pred=np.argmax(y_train_pred,axis=-1)
y_train_label=np.argmax(y_train,axis=-1)

y_test_pred=np.argmax(y_test_pred,axis=-1)
y_test_label=np.argmax(y_test,axis=-1)
y_test_pred,y_test_label

(array([32, 17, 47, ..., 29, 25,  3]), array([39, 16, 41, ..., 36, 22,  2]))

In [ ]:
def get_map(lt):
  map={}
  for i in lt:
    if i not in map.keys():
      map[i]=1
    else:
      map[i]+=1
  return map
pred=get_map(y_test_pred)
label=get_map(y_test_label)
map={}
for key in label.keys():
  if(abs(label[key]-pred[key])>30):
    map[key]=(label[key]-pred[key],label_fruit_map[key])
map#1,19,20,41,30,31

{0: (-33, 'acerola'),
 1: (251, 'apple'),
 4: (-32, 'black_berry'),
 8: (-32, 'custard_apple'),
 16: (60, 'jambul'),
 17: (-55, 'jujube'),
 19: (231, 'kumquat'),
 20: (230, 'lime'),
 22: (-51, 'lychee'),
 24: (-40, 'mango'),
 27: (55, 'orange'),
 29: (57, 'pear'),
 30: (245, 'pineapple'),
 31: (212, 'plumcot'),
 34: (-196, 'rambutan'),
 35: (-61, 'sapodilla'),
 37: (-126, 'ugli'),
 39: (-66, 'white_mulberry'),
 41: (241, 'zucchini'),
 42: (-154, 'manila tamarind'),
 43: (162, 'lillipilli')}

In [ ]:
lt=[1,19,20,41,30,31]
for i in lt:
  print(label_fruit_map[i])


apple
kumquat
lime
zucchini
pineapple
plumcot


In [ ]:
from sklearn.metrics import accuracy_score,classification_report
train_acc=accuracy_score(y_train_pred,y_train_label)
test_acc=accuracy_score(y_test_pred,y_test_label)
train_acc,test_acc

(0.029706717123935668, 0.02989593188268685)

In [ ]:
report=classification_report(y_test_label,y_test_pred)
print(report)

              precision    recall  f1-score   support

           0       0.88      0.97      0.93       311
           1       0.00      0.00      0.00       282
           2       0.00      0.00      0.00       290
           3       0.00      0.00      0.00       282
           4       0.00      0.00      0.00       251
           5       0.00      0.00      0.00       252
           6       0.00      0.00      0.00       256
           7       0.00      0.00      0.00       268
           8       0.00      0.00      0.00       250
           9       0.00      0.00      0.00       259
          10       0.00      0.00      0.00       253
          11       0.00      0.00      0.00       261
          12       0.01      0.01      0.01       258
          13       0.00      0.00      0.00       256
          14       0.00      0.00      0.00       258
          15       0.00      0.00      0.00       255
          16       0.00      0.00      0.00       319
          17       0.00    

/usr/local/lib/python3.7/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Recall and F-score are ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


Confusion Matrix

In [ ]:
from sklearn.metrics import confusion_matrix
from sklearn.metrics import ConfusionMatrixDisplay

cm=confusion_matrix(y_test_label,y_test_pred)
print(cm)

[[303   1   0 ...   1   0   0]
 [  1   0 253 ...   1   0   0]
 [  0   0   0 ...   2   0   0]
 ...
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]
 [  0   0   0 ...   0   0   0]]


In [ ]:
import os
fruit_lt=os.listdir('/content/drive/MyDrive/All fruits/Fruit')
fruit_lt,len(fruit_lt)

(['Acerola_fruit',
  'Apple_fruit',
  'Apricots_fruit',
  'Banana_fruit',
  'Blackberry_fruit',
  'Blueberry_fruit',
  'Carambola_fruit',
  'Cherry_fruit',
  'Chestnut_fruit',
  'Coconut_fruit',
  'Custard_apple_fruit',
  'Date_fruit',
  'Dragon_Fruit',
  'Fig_fruit',
  'Gooseberry_fruit',
  'Grapes_fruit',
  'Guava_fruit',
  'Jack_fruit',
  'Jambolan_fruit',
  'Jujube_fruit',
  'Kiwi_fruit',
  'Kumquat_fruit',
  'Lime_fruit',
  'Litchi_fruit',
  'Loquat_fruit',
  'Mamey_fruit',
  'Mango_fruit',
  'Mulberry_fruit',
  'Muskmelon_fruit',
  'Nectrine_fruit',
  'Olive_fruit',
  'Orange_fruit',
  'Papaya_fruit',
  'Pear_fruit',
  'Pineapple_fruit',
  'Plum_fruit',
  'Pomegranate_fruit',
  'Pummelo_fruit',
  'Peach_fruit',
  'Quince_fruit',
  'Rambutan_Fruit',
  'Sapodilla_fruit',
  'Soursop_fruit',
  'Strawberry_fruit',
  'Ugli_Fruit',
  'Ugni_fruit',
  'Water_Chestnut_fruit',
  'Watermelon_fruit',
  'White_Mulberry_fruit',
  'Yangmei_fruit',
  'apple.npy',
  'kumquat.npy',
  'lime.npy',
  

In [ ]:
fruit_map={}
for index,val in enumerate(fruit_lt):
  fruit_map[index]=val
fruit_map

{0: 'Acerola_fruit',
 1: 'Apple_fruit',
 2: 'Apricots_fruit',
 3: 'Banana_fruit',
 4: 'Blackberry_fruit',
 5: 'Blueberry_fruit',
 6: 'Carambola_fruit',
 7: 'Cherry_fruit',
 8: 'Chestnut_fruit',
 9: 'Coconut_fruit',
 10: 'Custard_apple_fruit',
 11: 'Date_fruit',
 12: 'Dragon_Fruit',
 13: 'Fig_fruit',
 14: 'Gooseberry_fruit',
 15: 'Grapes_fruit',
 16: 'Guava_fruit',
 17: 'Jack_fruit',
 18: 'Jambolan_fruit',
 19: 'Jujube_fruit',
 20: 'Kiwi_fruit',
 21: 'Kumquat_fruit',
 22: 'Lime_fruit',
 23: 'Litchi_fruit',
 24: 'Loquat_fruit',
 25: 'Mamey_fruit',
 26: 'Mango_fruit',
 27: 'Mulberry_fruit',
 28: 'Muskmelon_fruit',
 29: 'Nectrine_fruit',
 30: 'Olive_fruit',
 31: 'Orange_fruit',
 32: 'Papaya_fruit',
 33: 'Pear_fruit',
 34: 'Pineapple_fruit',
 35: 'Plum_fruit',
 36: 'Pomegranate_fruit',
 37: 'Pummelo_fruit',
 38: 'Peach_fruit',
 39: 'Quince_fruit',
 40: 'Rambutan_Fruit',
 41: 'Sapodilla_fruit',
 42: 'Soursop_fruit',
 43: 'Strawberry_fruit',
 44: 'Ugli_Fruit',
 45: 'Ugni_fruit',
 46: 'Water_C

In [ ]:
for index,row in enumerate(cm):
  count=0
  for j in range(len(row)):
    if(row[j]>0):
      count+=1
  if count>1:
    print(f'{fruit_map[index]}--->{row}')
  

Acerola_fruit--->[303   1   0   0   0   0   0   0   0   0   1   0   1   0   0   0   1   1
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   1   0   0   0
   0   0   0   0   0   0   0   1   0   0   0   1   0   0]
Apple_fruit--->[  1   0 253   0   0   0   1   0   0   0   0   0   1   0   0   0   0   1
   0   3   0   5   0   0   3   0   0   4   0   0   0   8   0   0   0   0
   0   0   0   0   0   0   0   0   0   1   0   1   0   0]
Apricots_fruit--->[  0   0   0 273   0   0   1   0   3   1   0   0   0   0   0   0   1   0
   0   0   0   0   0   1   3   2   0   0   1   0   1   0   0   1   0   0
   0   0   0   0   0   0   0   0   0   0   0   2   0   0]
Banana_fruit--->[  0   0   0   0 275   1   0   0   0   0   0   0   0   1   0   0   3   0
   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0   0
   2   0   0   0   0   0   0   0   0   0   0   0   0   0]
Blackberry_fruit--->[  0   0   0   0   0 246   0   0   1   0   0   0   0   3   0   0   0   0
   0   0   0   0   0   0 